spring.application.name=file-processor-worker

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations (Optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#AWS
aws.sqs.queue-url=https://sqs.us-east-2.amazonaws.com/942440204471/file-processor-queue
aws.s3.bucket-name=file-processor-dev-942440204471-us-east-2-an
